version: 2
updates:
# For GitHub Actions, we group minor and patch updates together, major updates are separate.
- package-ecosystem: github-actions
  directory: "/"
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
        - "minor"
        - "patch"
  schedule:
    interval: "weekly"
    time: "09:00"
    timezone: "Europe/Oslo"
    day: "monday"
  open-pull-requests-limit: 2

# For Terraform updates we only do security updates other bumps are manual.
- package-ecosystem: terraform
  directory: "/modules/postgresql-flex"
  schedule:
    interval: "daily"
    time: "09:00"
    timezone: "Europe/Oslo"
  open-pull-requests-limit: 0 # Security-updates only (https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file)
# For Terraform updates we only do security updates other bumps are manual.
- package-ecosystem: terraform
  directory: "/modules/postgresql"
  schedule:
    interval: "daily"
    time: "09:00"
    timezone: "Europe/Oslo"
  open-pull-requests-limit: 0 # Security-updates only (https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file)


# For Helm we group minor and patch updates together, major updates are separate.
- package-ecosystem: "gomod"
  directory: "/test/unit"
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
        - "minor"
        - "patch"
  schedule:
    interval: "weekly"
    time: "09:00"
    timezone: "Europe/Oslo"
    day: "monday"
  open-pull-requests-limit: 2
