name: Terraform Integration Tests

on:
  push:
    paths:
      - 'modules/postgresql-flex/**'
      - 'test/**'
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  test_postgresql:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Integration test Azure Postgresql module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - uses: actions/setup-go@v3
#        with:
#          go-version: 1.19
      - uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Test az auth federation
        uses: azure/CLI@v1
        with:
          inlineScript: |
              az resource list -g rg-app-tfmodules-dev --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#        - uses: hashicorp/setup-terraform@v2
#          with:
#            terraform_version: 0.15.1
#            terraform_wrapper: false
#        - id: 'get-credentials'
#          uses: 'google-github-actions/get-gke-credentials@v0'
#          with:
#            project_id: ${{ secrets.CLUSTER_PROJECT_ID }}
#            cluster_name: ${{ secrets.CLUSTER_NAME }}
#            location: ${{ secrets.CLUSTER_LOCATION }}
#        - name: Download Go Modules
#          working-directory: test/integration
#          run: go mod download
#        - name: Run Go Integration Tests
#          working-directory: test/integration
#          run: go test -tags=integration -timeout 30m
