name: Call Terraform Tests, Docs & Compliance

on:
  pull_request:
    branches:
      - main

jobs:
  tf-lint:
    name: Terraform Lint
    uses: entur/gha-terraform/.github/workflows/lint.yml@v2
    with:
      directory: "./modules/postgresql-flex"
  tf-lint2:
    name: Terraform Lint
    uses: entur/gha-terraform/.github/workflows/lint.yml@v2
    with:
      directory: "./modules/postgresql"
