name: Call Terraform Tests, Docs & Compliance

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  tf-lint-postgresql:
    name: Terraform Lint
    uses: entur/gha-terraform/.github/workflows/lint.yml@v2
    with:
      directory: ./modules/postgresql

  tf-lint-flex:
    name: Terraform Lint
    uses: entur/gha-terraform/.github/workflows/lint.yml@v2
    with:
      directory: ./modules/postgresql-flex
