name: Call Terraform Tests, Docs & Compliance

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # This will run the tests twice, one in the PR and one when Commiting to master.
  #  -> making sure the results appear in the "Security/Code Scan" tab in github.
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tf-tests:
    uses: entur/gh-workflows/.github/workflows/pr-tests-terraform.yml@main
    with:
      module_dirs: '["./modules/postgresql", "./modules/postgresql-flex", "./.github/workflows"]'
      tf_version: 0.15.1
