name: Call Terraform Tests, Docs & Compliance

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  tf-tests:
    uses: entur/gh-workflows/.github/workflows/pr-tests-terraform.yml@tf-validate-dir-override
    with:
      module_dirs: '["./modules/postgresql", "./modules/postgresql-flex"]'
      validate_dir_override: '["./modules/postgresql", "./examples/"]'
      tf_version: 0.13.2
